dist: xenial
language: elixir
elixir: 1.11
otp_release: 23.0
addons:
  postgresql: '9.6'
  ssh_known_hosts: helio.fm
services:
- postgresql
cache:
  directories:
  - _build
  - deps
env:
  global:
  - MIX_ENV=test
  - ELIXIR_ASSERT_TIMEOUT=2000
install:
- mix local.rebar --force
- mix local.hex --force
- mix deps.get
before_script:
- mix do ecto.create, ecto.migrate
script:
- mix do credo, coveralls.travis
before_deploy:
- openssl aes-256-cbc -K $encrypted_473de6575b5f_key -iv $encrypted_473de6575b5f_iv -in .deliver/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: mix deploy.prod
  on:
    branch: master
